### ISSUE TITLE
Unable to open backpack.

### ISSUE THREAD

**Issue by greystarMC** [P3pp3rF1y/SophisticatedBackpacks#1055]
**Describe the bug**
I am unable to open my backpack. I've tried both the hotkey and the right-clicking. The server admin gave me this stack trace. 

I had a few upgrades, magnet, deposit, and crafting. It was a diamond backpack.  I've also had other players pick it up and they are also not able to open it. 

The backpack is able to be emptied, either by hopper/pipe or by using the deposit upgrade and sneak clicking it on a chest. 

I'm playing the Minecolonies Dimensional Adventure modpack. https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure

It has happened twice using two different backpacks. The second time I was in the JEI crafting some items. I do not recall what. 

`[17May2024 21:01:42.314] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@5c3b3f80, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_41604_" is null
at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:147) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:143) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at ovh.corail.corail_pillar.recipe.RecipeSmallPillar.assemble(RecipeSmallPillar.java:61) ~[corail_pillar-1.20.1-5.9.1.jar%23581!/:5.9.1]
at ovh.corail.corail_pillar.recipe.RecipeSmallPillar.m_5874_(RecipeSmallPillar.java:19) ~[corail_pillar-1.20.1-5.9.1.jar%23581!/:5.9.1]
at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.updateCraftingResult(CraftingUpgradeContainer.java:144) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onCraftMatrixChanged(CraftingUpgradeContainer.java:125) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onInit(CraftingUpgradeContainer.java:121) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.addUpgradeSettingsContainers(StorageContainerMenuBase.java:118) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.initSlotsAndContainers(StorageContainerMenuBase.java:104) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.<init>(StorageContainerMenuBase.java:95) ~[sophisticatedcore-1.20.1-0.6.12.589.jar%23823!/:1.20.1-0.6.12.589]
at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.<init>(BackpackContainer.java:36) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23822!/:1.20.1-3.20.3.1034]
at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$use$9(BackpackItem.java:292) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23822!/:1.20.1-3.20.3.1034]
at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:204) ~[forge-1.20.1-47.2.20-universal.jar%23890!/:?]
at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:292) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23822!/:1.20.1-3.20.3.1034]
at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**To Reproduce**
I am unsure.

**Expected behavior**
The backpack should open.

**Versions**
<img width="719" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/82117997/09821c22-29ae-440a-8e2c-062d5fb9255e">

**Comment by P3pp3rF1y** [comment]
Appears that corail pillar has a broken recipe which is causing this crash. Because it's closed source mod I can't check their code to see what may be wrong. Try removing the mod, that should solve the issue.

**Comment by P3pp3rF1y** [comment]
Has corail pillar removal solve this issue for you?

**Comment by P3pp3rF1y** [comment]
closing given no follow up
