### ISSUE TITLE
Crafting in the backpack sometimes crashes the game

### ISSUE THREAD

**Issue by Chimpokosauce** [P3pp3rF1y/SophisticatedBackpacks#1088]
Sometimes when you craft something in the backpack it crashes the game.

	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.84.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Slot 9 not in valid range - [0,9)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206) ~[forge-1.20.1-47.1.84-universal.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:43) ~[forge-1.20.1-47.1.84-universal.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingItemHandler.m_6836_(CraftingItemHandler.java:85) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer$2.m_142406_(CraftingUpgradeContainer.java:78) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.lambda$doClick$15(StorageContainerMenuBase.java:1056) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_150430_(StorageContainerMenuBase.java:1054) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:AbstractContainerMenuAccessor,pl:mixin:APP:aether.mixins.json:common.accessor.AbstractContainerMenuAccessor,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:mixins.ae2things.json:CursedInternalSlotMixin,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_150399_(StorageContainerMenuBase.java:403) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.handleInventoryMouseClick(StorageScreenBase.java:771) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6597_(StorageScreenBase.java:760) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:botania_xplat.mixins.json:client.AbstractContainerScreenAccessor,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:ae2.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:ae2.mixins.json:ResizableSlotHighlightMixin,pl:mixin:APP:l2screentracker.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:adastra-common.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:findme-common.mixins.json:MixinSlotRenderer,pl:mixin:APP:inventoryessentials.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:polylib-forge.mixins.json:AbstractContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6375_(StorageScreenBase.java:828) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23720!/:1.20.1-0.6.22.611] {re:classloading}

Im currently using the FTB Presents Direwolf20 1.20 1.14.0 Modpack

**Comment by P3pp3rF1y** [comment]
Yup, this was report before. Some mod seems to have a recipe that tries to put items invalid slot. Some recipes return items into crafting grid when crafting (like vanilla cake recipe returns buckets after using milk from them) and in the case of this crash the recipe tries to put item back into 10th slot of the 9 crafting slots. Which obviously isn't going to work, vanilla crafting table probably just ignores that issue where sophisticated unfortunately crashes. I am going to add a bit of handling of that, probably dropping item on the ground and logging an error with the recipe registry name so that this can be reported to the mod author.

**Comment by P3pp3rF1y** [comment]
I have added a check that prevents this crash, log the id of recipe that has the issue and will drop the extra items that the recipe is trying to put outside of the crafting grid. New release of core is on CF (you will need to update SB and SS as well because they had changes related to new core version)
