### ISSUE TITLE
BackpackDynamicModel CRASH 

### ISSUE THREAD

**Issue by alexander2h** [P3pp3rF1y/SophisticatedBackpacks#1108]
Rendering item
java.lang.ArrayIndexOutOfBoundsException: Index 36 out of bounds for length 32
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5483_(QuadBakingVertexConsumer.java:58) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.createQuad(BackpackDynamicModel.java:322) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addFluid(BackpackDynamicModel.java:244) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.lambda$addRightSide$0(BackpackDynamicModel.java:203) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addRightSide(BackpackDynamicModel.java:203) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.getQuads(BackpackDynamicModel.java:161) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.minecraftforge.client.model.IDynamicBakedModel.m_213637_(IDynamicBakedModel.java:29) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackItemStackRenderer.m_108829_(BackpackItemStackRenderer.java:41) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.gui.GuiGraphics.m_280405_(GuiGraphics.java:575) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280053_(GuiGraphics.java:550) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280256_(GuiGraphics.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280092_(AbstractContainerScreen.java:236) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mafglib.mixins.json:MixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:IMixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:MixinHandledScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:103) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mafglib.mixins.json:MixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:IMixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:MixinHandledScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:744) ~[OptiFine_1.20.1_HD_U_I6.jar%23222!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1402) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Suspected Mod: 
	Sophisticated Backpacks (sophisticatedbackpacks), Version: 3.20.3.1034
		Issue tracker URL: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues
		at TRANSFORMER/sophisticatedbackpacks@3.20.3.1034/net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.createQuad(BackpackDynamicModel.java:322)
Stacktrace:
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5483_(QuadBakingVertexConsumer.java:58) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.createQuad(BackpackDynamicModel.java:322) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addFluid(BackpackDynamicModel.java:244) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.lambda$addRightSide$0(BackpackDynamicModel.java:203) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addRightSide(BackpackDynamicModel.java:203) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.getQuads(BackpackDynamicModel.java:161) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.minecraftforge.client.model.IDynamicBakedModel.m_213637_(IDynamicBakedModel.java:29) ~[forge-1.20.1-47.2.18-universal.jar%23217!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackItemStackRenderer.m_108829_(BackpackItemStackRenderer.java:41) ~[sophisticatedbackpacks-1.20.1-3.20.3.1034.jar%23199!/:1.20.1-3.20.3.1034] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.gui.GuiGraphics.m_280405_(GuiGraphics.java:575) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280053_(GuiGraphics.java:550) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280256_(GuiGraphics.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280092_(AbstractContainerScreen.java:236) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mafglib.mixins.json:MixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:IMixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:MixinHandledScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:103) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mafglib.mixins.json:MixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:IMixinHandledScreen,pl:mixin:APP:forgematica.mixins.json:MixinHandledScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen

**Comment by P3pp3rF1y** [comment]
is this with sophisticated only in the modpack? What have you got in your backpack? (tank / battery / any item shown on backpack)

**Comment by alexander2h** [comment]
When I found that the stacking quantity of backpack items reached 8192, this problem began to occur. I also installed OptiFine_1.20.1.HD_U_i6 MouseTweaks-forge-mc1.20.1-2.25.1、SpartanWeaponry-1.20.1-forge-3.1.1-all。

**Comment by alexander2h** [comment]
When I found that the stacking quantity of backpack items reached 8192, this problem began to occur. I also installed OptiFine_1.20.1.HD_U_i6 MouseTweaks-forge-mc1.20.1-2.25.1、SpartanWeaponry-1.20.1-forge-3.1.1-all。
