### ISSUE TITLE
Epicfightx bclib x sophiscated

### ISSUE THREAD

**Issue by WarSD** [P3pp3rF1y/SophisticatedBackpacks#1128]
It's a very specific bug that makes you unable to place blocks after traveling for a while in the end when you create a server in 1.20.1, and if someone travels through the end for a while it activates this and you have to restart the server to maybe get it back to normal, but after a few restarts it goes back to normal for sure. Problem is that it's impossible to place blocks in most places, but you can replace them on the grass and also on certain vertical lines on the map, randomly.

>....java.lang.Exception
        at TRANSFORMER/epicfight@20.8.8/yesman.epicfight.events.PlayerEvents.test(PlayerEvents.java:118)
        at TRANSFORMER/epicfight@20.8.8/yesman.epicfight.events.__PlayerEvents_test_Open.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@47.3.0/net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:213)
        at TRANSFORMER/sophisticatedbackpacks@3.20.6.1064/net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:292)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by P3pp3rF1y** [comment]
based on that short stack I can only see that someone was trying to open backpack and have no idea what kind of issue was raised there. So I definitely need much more info on how I can recreate. This definitely wouldn't trigger on block placement btw.

**Comment by P3pp3rF1y** [comment]
any update on this or should I just close?

**Comment by P3pp3rF1y** [comment]
closing given no response
