### ISSUE TITLE
Backpacks data getting wiped

### ISSUE THREAD

**Issue by Kamisoi** [P3pp3rF1y/SophisticatedBackpacks#1184]
**Describe the bug**
Backpacks are getting cleared from time to time on server.
Exact log:
```java
[23Oct2024 03:41:43.977] [Server thread/ERROR] [net.minecraft.world.level.storage.DimensionDataStorage/]: Error loading saved data: sophisticatedbackpacks
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackStorage.get(BackpackStorage.java:41) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23584!/:1.20.1-3.20.5.1044]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.getBackpackContentsNbt(BackpackWrapper.java:148) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23584!/:1.20.1-3.20.5.1044]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.getUpgradeHandler(BackpackWrapper.java:219) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23584!/:1.20.1-3.20.5.1044]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.getInventoryForInputOutput(BackpackWrapper.java:158) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23584!/:1.20.1-3.20.5.1044]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackBlockEntity.lambda$getCapability$1(BackpackBlockEntity.java:148) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23584!/:1.20.1-3.20.5.1044]
```

**To Reproduce**
Unknown - behavior mostly experienced on Craft to Exile 2 modpack (v0.6.2 to be exact).

**Expected behavior**
For backpack player data to not get corrupted and correctly load up, without clearing player's inventory. Ideally, if no clear solution can be defined - I'd rather get server crash than overwrite all backpacks data.

**Versions**
1.20.1-3.20.5.1044

**Comment by P3pp3rF1y** [comment]
That's easy. this basically means that your data got corrupted in some way probably because of server crash that caused it to break while it was saving the data. you will need to restore from backup.
