### ISSUE TITLE
[Bug] Server crash on opening loot backpack from mobs

### ISSUE THREAD

**Issue by Radon8472** [P3pp3rF1y/SophisticatedBackpacks#1243]
**Describe the bug**
We upgraded the backpacks mod (and core mod). 
After the update we got several server crashes that accour when opening backpacks that where dropped by mobs.

The crash log shows following message.

**To Reproduce**
1. Kill mobs until a backpack is dropped (or take an existing backpack that was dropped by mobs and never opened)
2.  Open the backpack
3. Look into crash-logs/

**Expected behavior**
No error should happen, and backpack should oben

**Versions**
- sophisticatedcore-1.20.1-1.0.0.807.jar
- sophisticatedbackpacks-1.20.1-3.20.5.1044.jar

**Bug-report**
```
java.lang.NoSuchMethodError: 'java.util.List net.p3pp3rf1y.sophisticatedcore.util.LootHelper.getLoot(net.minecraft.resources.ResourceLocation, net.minecraft.server.MinecraftServer, net.minecraft.server.level.ServerLevel, net.minecraft.world.entity.Entity)'
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.fillWithLootFromTable(BackpackWrapper.java:492) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.lambda$fillWithLoot$12(BackpackWrapper.java:429) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.wrapper.BackpackWrapper.fillWithLoot(BackpackWrapper.java:429) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.<init>(StorageContainerMenuBase.java:97) ~[sophisticatedcore-1.20.1-1.0.0.807.jar%23494!/:1.20.1-1.0.0.807] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.<init>(BackpackContainer.java:36) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$use$9(BackpackItem.java:292) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:204) ~[forge-1.20.1-47.2.16-universal.jar%23528!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:292) ~[sophisticatedbackpacks-1.20.1-3.20.5.1044.jar%23493!/:1.20.1-3.20.5.1044] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:grieflogger-common.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:interact,re:computing_frames,pl:accesstransformer:B,xf:fml:libx:interact,re:classloading,pl:accesstransformer:B,xf:fml:libx:interact,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerGameModeAccessor,pl:mixin:APP:questsadditions.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl,pl:mixin:APP:ad_astra-common.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:toofast.mixins.json:MixinServerNetPlayHandler,pl:mixin:APP:mixins.dcintegration.json:MixinNetHandlerPlayServer,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23523!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

```

**Comment by P3pp3rF1y** [comment]
NoSuchMethodError usually means that you have incorrect version of the dependency. In this case it's 8 months old version of backpacks that is too old for month old version of core. Just update and issue fixed
