### ISSUE TITLE
Pressing "E" kicks me

### ISSUE THREAD

**Issue by MultyRain1** [P3pp3rF1y/SophisticatedBackpacks#1249]
On my Aternos server I can't press "E" to open my inventory. Whenever I do I get kicked. This is in every gamemode and here is the crash message:

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: sophisticatedbackpacks:smithing_upgrade

Does anyone know how to fix this. I also use alot of other mods too so maybe they are the problem.
![1](https://github.com/user-attachments/assets/c9c78413-5390-402f-afdf-3ed92559a48c)
![2](https://github.com/user-attachments/assets/a0409ea8-9117-4d02-86f1-367ce206b214)
![3](https://github.com/user-attachments/assets/93e7c3b7-7d40-4893-bca3-00b7cdad8642)
![4](https://github.com/user-attachments/assets/e62bdb9e-810d-4888-bf06-daa37f286f10)
![5](https://github.com/user-attachments/assets/20d3fa14-c09d-45bf-bdfb-924ec5e28b08)
![6](https://github.com/user-attachments/assets/3652500e-d17f-4aeb-a76a-7d1413ea87d8)
![7](https://github.com/user-attachments/assets/faa02e7c-252d-43b4-b758-70ebbccfadd9)

**Comment by P3pp3rF1y** [comment]
have you got the same version of SB on the server / client? Is there more detail for that exception in the log?

**Comment by MultyRain1** [comment]
> have you got the same version of SB on the server / client? Is there more detail for that exception in the log?

I do not know to where the crash code is usefull to, so there is a bit of it.

java.lang.NullPointerException: Registry Object not present: sophisticatedbackpacks:smithing_upgrade
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.3.0-universal.jar%23273!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_registry_lambda.RegistryObjectMixin from mod modernfix,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems.lambda$static$47(ModItems.java:255) ~[sophisticatedbackpacks-1.20.1-3.21.1.1161.jar%23253!/:1.20.1-3.21.1.1161]

**Comment by MultyRain1** [comment]
btw yes i have the same versions

**Comment by MultyRain1** [comment]
I have somehow managed to fix it. I just reinstalled it (again) and now it works. Still thanks for trying to help
