### ISSUE TITLE
Upgrade Slot server crash

### ISSUE THREAD

**Issue by TheRedLancer** [P3pp3rF1y/SophisticatedBackpacks#129]
**Describe the bug**
I accidentally placed a stack of cactus blocks in the upgrade slot and it crashed not only my game, but the server. 

**To Reproduce**
1. Open backpack
2. Place Crafting Upgrade in upgrade slot
3. Replace Cactus stack for Crafting Upgrade

**Expected behavior**
Game and server crashes. I have tried it in a single player world and it has the same behavior.

**Screenshots**
```
[29Apr2021 00:52:10.204] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: TheRedLancer lost connection: Disconnected
[29Apr2021 00:52:10.204] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: TheRedLancer left the game
[29Apr2021 00:52:10.210] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.ClassCastException: class net.minecraft.item.BlockItem cannot be cast to class net.p3pp3rf1y.sophisticatedbackpacks.api.IBackpackUpgradeItem (net.minecraft.item.BlockItem and net.p3pp3rf1y.sophisticatedbackpacks.api.IBackpackUpgradeItem are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @462abec3)
	at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer$BackpackUpgradeSlot.func_82869_a(BackpackContainer.java:560) ~[sophisticatedbackpacks:1.16.4-2.2.7.219]
	at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.isInventorySlotInUpgradeTab(BackpackContainer.java:1092) ~[sophisticatedbackpacks:1.16.4-2.2.7.219]
	at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.func_75134_a(BackpackContainer.java:1079) ~[sophisticatedbackpacks:1.16.4-2.2.7.219]
	at net.minecraft.entity.player.PlayerEntity.remove(PlayerEntity.java:1239) ~[?:?]
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:967) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:964) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:338) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1021) ~[?:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:368) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:149) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[29Apr2021 00:52:10.275] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 457d45f3-2f01-482a-a6ca-34f28b5f273b
```

**Versions**
Version: 1.16.4-2.2.7.219

**Comment by P3pp3rF1y** [comment]
Just update to latest version. Bug with other stuff going into upgrade slots has been fixed for at least a few weeks now. And latest version even gracefully handles backpacks that got something put in there before the fix
