### ISSUE TITLE
Crash when starting server

### ISSUE THREAD

**Issue by Coryy82** [P3pp3rF1y/SophisticatedBackpacks#138]
**Describe the bug**
I was trying to create a modded server but sophisticated backpacks failed to load correctly, I tried changing downloading another version of the mod to a newer one but it didn't work. 

### Crash log
-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-4.0.0.jar:?] {}
-- MOD sophisticatedbackpacks --
Details:
	Mod File: sophisticatedbackpacks-1.16.4-2.4.0.259.jar
	Failure message: Sophisticated Backpacks (sophisticatedbackpacks) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy$$Lambda$3323/0x000000001374f1c0@8446fb16
	Mod Version: property(class java.lang.String, provider(?))
	Mod Issue URL: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues
	Exception message: java.lang.IllegalStateException: Failed to resolve consumer event type: net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy$$Lambda$3323/0x000000001374f1c0@8446fb16
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:162) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:173) ~[eventbus-4.0.0.jar:?] {}
	at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy.registerHandlers(CommonProxy.java:65) ~[sophisticatedbackpacks:property(class java.lang.String, provider(?))] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.SophisticatedBackpacks.<init>(SophisticatedBackpacks.java:41) ~[sophisticatedbackpacks:property(class java.lang.String, provider(?))] {re:classloading}
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:1.8.0_282] {}
	at java.lang.Class.newInstance(Class.java:2015) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3112/0x0000000000000000.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3268/0x0000000000000000.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_282] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_282] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282] {}

### System Details
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_282, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20210120_972 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08), Eclipse OpenJ9
	Memory: 8581619432 bytes (8184 MB) / 10737418240 bytes (10240 MB) up to 24696061952 bytes (23552 MB)
	CPUs: 8
	JVM Flags: 23 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.282.8-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xms10G -Xmx23G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forgeserver.jar object_holder_definalize PLUGINSERVICE 
		/forgeserver.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forgeserver.jar capability_inject_definalize PLUGINSERVICE 
		/forgeserver.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.5_HD_U_G8_pre11.jar OptiFine TRANSFORMATIONSERVICE 
		/forgeserver.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1

**To Reproduce**
1. Create Server
2. Open Server
3. Crash

**Expected behavior**
Expected to generate world normally

**Versions**
_Mod:_ sophisticatedbackpacks-1.16.4-2.4.0.259.jar
_Forge version:_ 36.0.1

**Comment by P3pp3rF1y** [comment]
Forge isn't compatible with OpenJ9 JDK so you need to use a different one. As far as I know pretty much any other works. Nothing I can do about this on my side as it's an issue with how OpenJ9 loads classes which then breaks Forge functionality that registers event listeners from mods.
