### ISSUE TITLE
Game crashes when joining Single Player hosted LAN server.

### ISSUE THREAD

**Issue by ThinkWithPbody** [P3pp3rF1y/SophisticatedBackpacks#215]
I can run the game with no problem and local host from single player menu, but any other players connecting will crash. 
Generate a new save and the problem persists. 
Disabling Optifine/Twilight Forest/Some other mods did not fix it. 
Disabling Sophisticated Backpacks fixes the problem. 

Note: I used to have these same mods on a dedicated server around May 2021, and the game ran fine. I've updated all mods since then, but nothing more.

**Crash log** from one of the players (the other crash logs contain exactly the same message):

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 8/22/21 7:43 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat.lambda$new$5(CuriosCompat.java:44) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat$$Lambda$9785/1883294766.run(Unknown Source) ~[?:?] {}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.initialize(PlayerInventoryProvider.java:77) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.getBackpackFromRendered(PlayerInventoryProvider.java:56) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackLayerRenderer.render(BackpackLayerRenderer.java:57) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackLayerRenderer.func_225628_a_(BackpackLayerRenderer.java:33) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/275609562.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat.lambda$new$5(CuriosCompat.java:44) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat$$Lambda$9785/1883294766.run(Unknown Source) ~[?:?] {}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.initialize(PlayerInventoryProvider.java:77) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.getBackpackFromRendered(PlayerInventoryProvider.java:56) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackLayerRenderer.render(BackpackLayerRenderer.java:57) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackLayerRenderer.func_225628_a_(BackpackLayerRenderer.java:33) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.RemoteClientPlayerEntity)
	Entity ID: 322
	Entity Name: 30_Salt
	Entity's Exact location: -59.53, 63.00, -170.60
	Entity's Block location: World: (-60,63,-171), Chunk: (at 4,3,5 in -4,-11; contains blocks -64,0,-176 to -49,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.15, -0.08, 0.16
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@5c9d433a
	Location: -0.03,-1.62,1.90 - World: (-1,-2,1), Chunk: (at 15,-1,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 187.03125
	Delta: 0.220047
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['nativefaithh'/30951, l='ClientLevel', x=-59.50, y=63.00, z=-172.50], RemoteClientPlayerEntity['30_Salt'/322, l='ClientLevel', x=-59.53, y=63.00, z=-170.60]]
	Chunk stats: Client Chunk Cache: 625, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-60,63,-172), Chunk: (at 4,3,4 in -4,-11; contains blocks -64,0,-176 to -49,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 6845 game time, 6845 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/275609562.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 982283344 bytes (936 MB) / 2469920768 bytes (2355 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.14.0
	Mod List: 
		torchslabmod-1.16.4_v1.6.19.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |Manifest: NOSIGNATURE
		SereneShrubbery-1.16.5-1.1.0.jar                  |Serene Shrubbery              |serene_shrubbery              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.118.jar                          |Just Enough Items             |jei                           |7.7.1.118           |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.1.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.1      |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.14.jar                     |TerraForged                   |terraforged                   |0.2.14              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		XaerosWorldMap_1.16.1_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.16.1              |DONE      |Manifest: NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |DONE      |Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.0.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.0       |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.121-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.121    |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.2.4.316.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.2.4.316    |DONE      |Manifest: NOSIGNATURE
		creeperconfetti-3.7.jar                           |Creeper Confetti              |creeperconfetti               |3.7                 |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		bedspreads-forge-1.16.5-5.1.0.2.jar               |Bedspreads                    |bedspreads                    |1.16.5-5.1.0.2      |DONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v1.2-1.16.3.jar                    |Pick Up Notifier              |pickupnotifier                |1.2                 |DONE      |Manifest: d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		SnowRealMagic-1.16.4-2.5.7.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.7               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.23-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.23-mc1.16.5       |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		JustEnoughResources-1.16.5-0.12.1.127.jar         |Just Enough Resources         |jeresources                   |0.12.1.127          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.16.5-4.0.546-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		w2w-1.16.1-0.0.5.2.jar                            |w2w                           |w2w                           |NONE                |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
		createplus-1.16.4_v0.3.2.1.jar                    |Create Plus                   |createplus                    |1.16.4_v0.3.2.1     |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.1.252.jar                   |Tinkers' Construct            |tconstruct                    |3.1.1.252           |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |Manifest: NOSIGNATURE
		fastfurnaceminusreplacement-1.1-1.16.3.jar        |Fast Furnace Minus Replacement|fastfurnaceminusreplacement   |1.1-1.16.3          |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.482-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.482   |DONE      |Manifest: NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.2.8.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.2.8        |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.3.jar                           |Flywheel                      |flywheel                      |1.16-0.2.3          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.115.jar                         |Mantle                        |mantle                        |1.6.115             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.15.1_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.15.1             |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |Manifest: NOSIGNATURE
		betterbiomeblend-1.16.4-1.2.9-forge.jar           |Better Biome Blend            |betterbiomeblend              |1.16.4-1.2.9-forge  |DONE      |Manifest: NOSIGNATURE
		baubely-heart-canisters-1.16.5-1.1.10.jar         |Baubley Heart Canisters       |bhc                           |1.16.5-1.1.10       |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.72m.jar                     |Performant                    |performant                    |3.56m               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.1.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.1.0      |DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.3.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.3      |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.20.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.20       |DONE      |Manifest: NOSIGNATURE
		fastbenchminusreplacement-1.4.jar                 |FastWorkbench Minus Replacemen|fastbenchminusreplacement     |1.4                 |DONE      |Manifest: NOSIGNATURE
		chickensshed-1.16.5-1.1.jar                       |ChickensShed                  |chickensshed                  |1.16.5-1.1          |DONE      |Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta24.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta24|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |DONE      |Manifest: NOSIGNATURE
		DynamicTreesBOP-1.16.5-2.0.6.jar                  |Dynamic Trees for Biomes o' Pl|dtbop                         |1.16.5-2.0.6        |DONE      |Manifest: NOSIGNATURE
		DynamicTreesQuark-1.16.5-2.1.0.jar                |Dynamic Trees for Quark       |dtquark                       |1.16.5-2.1.0        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		BetterFoliage-2.7.1-Forge-1.16.5.jar              |Better Foliage                |betterfoliage                 |2.7.1               |DONE      |Manifest: NOSIGNATURE
		DynamicTreesTerraForged-1.16.5-1.0.0.jar          |Dynamic Trees for TerraForged |dtterraforged                 |1.16.5-1.0.0        |DONE      |Manifest: NOSIGNATURE
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f94f7214-4832-4ff4-b98c-635e3fd078ab
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:terraforged
		snowrealmagic:world
	Launched Version: forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
```

Forge version 36.2.0. 
Please let me know if there's anything more I can add to help you pinpoint the problem. 
I think sophisticated backpacks is the best mod of its kind and I can not tolerate Minecraft without it. Thank you in advance for your time.

**Comment by Gavin456b** [comment]
I am also having this problem

**Comment by P3pp3rF1y** [comment]
The fix for this is up on curseforge, but CF is taking very long to finish processing the file today (uploaded it 90 mins ago). Hopefully they will finish that soon.

**Comment by P3pp3rF1y** [comment]
And looks like it helps to complain a bit - they just finished with it so the fixed version is up on CF.

**Comment by ThinkWithPbody** [comment]
I understood none of that so I believe I just need to wait a bit for curseforge to fix the problem? Would I need to use a newer version of forge when the fix comes out? 

I really appreciate the work you've put into this mod! Thanks.

**Comment by P3pp3rF1y** [comment]
the fix is already uploaded on curseforge as I said above, no reason to update forge either as I haven't updated the verison SBP depends on
