### ISSUE TITLE
Curios API render crash

### ISSUE THREAD

**Issue by DiavalTheCrow** [P3pp3rF1y/SophisticatedBackpacks#218]
Found a crash, rendering issues with Curios API.

-- Head --
Thread: Render thread
Stacktrace:
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat.lambda$new$5(CuriosCompat.java:44) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.curios.CuriosCompat$$Lambda$24349/1376414471.run(Unknown Source) ~[?:?] {}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.initialize(PlayerInventoryProvider.java:77) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.getPlayerInventoryHandlers(PlayerInventoryProvider.java:70) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.util.PlayerInventoryProvider.runOnBackpacks(PlayerInventoryProvider.java:86) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy.onBlockClick(CommonProxy.java:128) ~[?:1.16.5-3.2.4.316] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy$$Lambda$8842/2060163343.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3036/483244772.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2674/393085481.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:816) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_plus.mixins.json:ForgeHooksMixin,pl:mixin:APP:locks.mixins.json:ForgeHooksAccessor,pl:mixin:APP:morecfm.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:140) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}

Mod version that you're using. Version of forge may also be helpful in some cases
- sophisticatedbackpacks-1.16.5-3.2.4.316.

**Comment by P3pp3rF1y** [comment]
Fixed version is up on CF
