### ISSUE TITLE
Crash when using Wildfire's Female Gender Mod in conjunction with Sophisticated Backpacks.

### ISSUE THREAD

**Issue by retcinder** [P3pp3rF1y/SophisticatedBackpacks#386]
**Describe the bug**
When the Wildfire's Female Gender Mod has specific settings, equipping a backback in the chestplate slot will crash the game and anyone who has you visible.
Crash Log:
```
---- Minecraft Crash Report ----
// You're mean.

Time: 05/01/2022, 20:39
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:2247) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1881) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1539) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1156) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:2247) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1881) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1539) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Azreigh'/8601, l='ClientLevel', x=439.14, y=72.00, z=31.84]]
	Chunk stats: 289, 162
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4506846 game time, 6778065 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2200655360 bytes (2098 MiB) / 3925868544 bytes (3744 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 520
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1191
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 13711.50
	Virtual memory used (MB): 11586.66
	Swap memory total (MB): 5649.88
	Swap memory used (MB): 1161.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.1-forge-39.0.9
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Intel(R) HD Graphics 520 GL version 3.2.0 - Build 30.0.101.1191, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 84
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 30.0.101.1191
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		block_variants-1.18-3.0.jar                       |Vanilla Block Variants        |block_variants                |3.0                 |DONE      |Manifest: NOSIGNATURE
		[Forge]+Wildfire+Female+Gender+Mod-2.8.1.jar      |Wildfire's Female Gender Mod  |wildfire_gender               |2.8.1               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.15.0.494.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.15.0.494   |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.61-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.61    |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.1.1.48.jar                           |Just Enough Items             |jei                           |9.1.1.48            |DONE      |Manifest: NOSIGNATURE
		Enhanced-Farming-1.18.1-1.2.5.jar                 |Enhanced Farming              |enhancedfarming               |1.2.5               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.4.0.jar                             |wthit                         |wthit                         |4.4.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.9-universal.jar                 |Forge                         |forge                         |39.0.9              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-forge-1.18-0.5.0a.jar                    |Flywheel                      |flywheel                      |1.18-0.5.0a         |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4b.jar                         |Create                        |create                        |0.4b                |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.22.6_Forge_1.18.jar             |Xaero's Minimap               |xaerominimap                  |21.22.6             |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		[1.18.1]+SecurityCraft+v1.9.0.2-beta1.jar         |SecurityCraft                 |securitycraft                 |1.9.0.2-beta1       |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 89974a83-448e-484a-a061-a066b68fb97a
	FML: 39.0
	Forge: net.minecraftforge:39.0.9
```
Mods causing the bug: Sophisticated Backpacks, Wildfire's Female Gender Mod (Forge)

**To Reproduce**
1. Open a world.
2. Set gender to female (in Wildfire's Gender Mod) and set breast size to anything over 0%.
3. Equip a backpack in the chestplate slot.

**Expected behavior**
Equipping a backpack shouldn't crash the game due to `java.lang.IllegalStateException: Pose stack not empty`. Instead, the game should handle it fine.

**Versions**
Forge 39.0.9
Sophisticated Backpacks 1.18.1-3.15.0.494
Wildfire's Female Gender Mod 2.8.1

**Comment by P3pp3rF1y** [comment]
I have double checked my code, but SBP isn't responsible for rendering the PoseStack. It doesn't help that the Female Gender Mod is closed source, but I am guessing that they are not properly rendering PoseStack after all of the layers have completed their rendering logic. Also SBP works without any issue even with other mods that change rendering of the player so I am calling this the other mod's issue and nothing that can be fixed on my side.
