### ISSUE TITLE
gold backpack crash

### ISSUE THREAD

**Issue by kazukomi** [P3pp3rF1y/SophisticatedBackpacks#444]
i upgraded my backpack to gold and now my game crashes when i try to open it and i have very important things in there that i cant get out here is the crash log:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/20/22, 5:04 PM
Description: Rendering screen

java.lang.IllegalArgumentException: guiTop must be >= 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at mezz.jei.gui.overlay.GuiProperties.<init>(GuiProperties.java:110) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.overlay.GuiProperties.create(GuiProperties.java:46) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.GuiScreenHelper.getGuiProperties(GuiScreenHelper.java:73) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.updateScreen(IngredientListOverlay.java:97) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:70) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraft.client.gui.screens.Screen.m_96558_(Screen.java:450) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_7333_(Screen.java:444) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6305_(StorageScreenBase.java:221) ~[sophisticatedbackpacks-1.18.2-3.15.17.559.jar%2361!/:1.18.2-3.15.17.559] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:381) ~[forge-1.18.2-40.0.15-universal.jar%2369!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374) ~[forge-1.18.2-40.0.15-universal.jar%2369!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.15.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at mezz.jei.gui.overlay.GuiProperties.<init>(GuiProperties.java:110) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.overlay.GuiProperties.create(GuiProperties.java:46) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.GuiScreenHelper.getGuiProperties(GuiScreenHelper.java:73) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.updateScreen(IngredientListOverlay.java:97) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:70) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at mezz.jei.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.18.2-9.5.0.132.jar%2357!/:9.5.0.132] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraft.client.gui.screens.Screen.m_96558_(Screen.java:450) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_7333_(Screen.java:444) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6305_(StorageScreenBase.java:221) ~[sophisticatedbackpacks-1.18.2-3.15.17.559.jar%2361!/:1.18.2-3.15.17.559] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:381) ~[forge-1.18.2-40.0.15-universal.jar%2369!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374) ~[forge-1.18.2-40.0.15-universal.jar%2369!/:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
	Mouse location: Scaled: (228, 128). Absolute: (683.000000, 384.000000)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.15.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['gomentsukki'/168, l='ClientLevel', x=154.37, y=-5.00, z=60.45]]
	Chunk stats: 361, 210
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,113,32), Section: (at 0,1,0 in 0,7,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 183589 game time, 200992 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:406) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2257) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:680) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2365!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.15.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, Fat Cat.zip, cathotbar.zip, Better+Leaves+Addon+V2.8-1.18.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 934694696 bytes (891 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=26.20.11002.12
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15145.71
	Virtual memory used (MB): 9398.34
	Swap memory total (MB): 896.00
	Swap memory used (MB): 48.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.0.15
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.13558 Core Profile Forward-Compatible Context 26.20.11002.12, ATI Technologies Inc.
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/Fat Cat.zip (incompatible), file/cathotbar.zip (incompatible), file/Better+Leaves+Addon+V2.8-1.18.zip
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['gomentsukki'/168, l='ServerLevel[stepsis ughh]', x=154.37, y=-5.00, z=60.45]]
	Data Packs: vanilla, mod:libx, mod:terrablender (incompatible), mod:buildersaddition (incompatible), mod:sophisticatedbackpacks (incompatible), mod:morevanillalib, mod:biomesoplenty (incompatible), mod:balm (incompatible), mod:morevanillatools, mod:jei (incompatible), mod:forge (incompatible), mod:waystones (incompatible), mod:exlinefurniture (incompatible), mod:croptopia (incompatible), mod:xaerominimap
	World Generation: Stable
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		LibX-1.18.2-3.2.2.jar                             |LibX                          |libx                          |1.18.2-3.2.2        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.91.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.91     |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.18.2-20220308a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.2-20220308a    |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.15.17.559.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.15.17.559  |DONE      |Manifest: NOSIGNATURE
		MoreVanillaLib-1.18.2-3.1.1.jar                   |MoreVanillaLib                |morevanillalib                |1.18.2-3.1.1        |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.107-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.107   |DONE      |Manifest: NOSIGNATURE
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |DONE      |Manifest: NOSIGNATURE
		MoreVanillaTools-1.18.2-4.1.1.jar                 |MoreVanillaTools              |morevanillatools              |1.18.2-4.1.1        |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.0.132.jar                          |Just Enough Items             |jei                           |9.5.0.132           |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.0.15-universal.jar                |Forge                         |forge                         |40.0.15             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Xaeros_Minimap_22.3.1_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |22.3.1              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		exlinefurniture-forge-1.18.2-v2.05.jar            |Exline's Furniture            |exlinefurniture               |1.18.2              |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18.2-FORGE-1.8.2.jar                  |Croptopia                     |croptopia                     |1.8.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 91fe1faf-382a-442c-a79b-0972fe5a7585
	FML: 40.0
	Forge: net.minecraftforge:40.0.15

**Comment by P3pp3rF1y** [comment]
just download latest 1.18.2 version of sophisticatedbackpacks and jei and you are set
