### ISSUE TITLE
player can't join server! 

### ISSUE THREAD

**Issue by axaluss** [P3pp3rF1y/SophisticatedBackpacks#626]
my gdlauncher modpack: [MyModpack-1.0.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9833388/MyModpack-1.0.zip)

- sophisticatedbackpacks-1.18.1-3.15.15.550.jar
![image](https://user-images.githubusercontent.com/342630/197042652-fe230a29-db0e-406a-bfb9-4e9f5ccbf519.png)

I don't know what action caused this. there is a bunch of items.
This is the player inventory:
[Downloads.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9833400/Downloads.zip)

you can open these dat files with [ntbexplorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)

my stacktrace: 
```
[15:23:00] [Server thread/WARN]: Failed to handle packet for /209.150.43.153:55771
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.size()" because the return value of "java.util.Map.get(Object)" is null
        at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertIntoSlotsThatMatchStack(InventoryHandlerSlotTracker.java:167) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertItemIntoHandler(InventoryHandlerSlotTracker.java:124) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insertItem(InventoryHandler.java:306) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedcore.upgrades.magnet.MagnetUpgradeWrapper.tryToInsertItem(MagnetUpgradeWrapper.java:188) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedcore.upgrades.magnet.MagnetUpgradeWrapper.pickupItems(MagnetUpgradeWrapper.java:146) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedcore.upgrades.magnet.MagnetUpgradeWrapper.tick(MagnetUpgradeWrapper.java:77) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$inventoryTick$10(BackpackItem.java:328) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$inventoryTick$11(BackpackItem.java:328) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.1-39.1.2-universal.jar%23142!/:?]
        at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_6883_(BackpackItem.java:326) ~[sophisticatedbackpacks-1.18.1-3.15.15.550.jar%23119!/:1.18.1-3.15.15.550]
        at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:484) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:235) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.world.entity.player.Player.m_8107_(Player.java:489) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2249) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%23138!/:?]

```

**Comment by evilspacebunny** [comment]
Also have players on a ATM7 server having the ticking player issue as well. 
https://pastebin.com/tRNDC0yJ

**Comment by P3pp3rF1y** [comment]
fixed in the latest version of sophisticatedcore on curseforge
