### ISSUE TITLE
Backpack With Experience Pump, Tank, and Advanced Magnet Upgrade Causing Crash After Storing XP

### ISSUE THREAD

**Issue by puentesca** [P3pp3rF1y/SophisticatedBackpacks#652]
**Describe the bug**
When playing with an empty, diamond backpack with the tank upgrade, advanced magnet upgrade, and experience pump upgrade. the game crashes after storing XP in the tank section of the backpack. From the looks of it, it looks like the textures aren't working correctly.

Crash Report: 
Time: 2022-12-01 04:28:15
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:132) ~[forge-1.19.2-43.1.58-universal.jar%23205!/:?] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.createQuad(BackpackDynamicModel.java:328) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addFluid(BackpackDynamicModel.java:249) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.lambda$addRightSide$0(BackpackDynamicModel.java:208) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addRightSide(BackpackDynamicModel.java:208) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.getQuads(BackpackDynamicModel.java:166) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.minecraftforge.client.model.IDynamicBakedModel.m_213637_(IDynamicBakedModel.java:29) ~[forge-1.19.2-43.1.58-universal.jar%23205!/:?] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java:137) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackItemStackRenderer.m_108829_(BackpackItemStackRenderer.java:41) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:268) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:417) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109322_(ItemInHandRenderer.java:138) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:339) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.GameRenderer.renderHand(GameRenderer.java:1088) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:1049) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1603) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1191) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.58.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:132) ~[forge-1.19.2-43.1.58-universal.jar%23205!/:?] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.createQuad(BackpackDynamicModel.java:328) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addFluid(BackpackDynamicModel.java:249) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.lambda$addRightSide$0(BackpackDynamicModel.java:208) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.addRightSide(BackpackDynamicModel.java:208) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackDynamicModel$BackpackBakedModel.getQuads(BackpackDynamicModel.java:166) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.minecraftforge.client.model.IDynamicBakedModel.m_213637_(IDynamicBakedModel.java:29) ~[forge-1.19.2-43.1.58-universal.jar%23205!/:?] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java:137) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.p3pp3rf1y.sophisticatedbackpacks.client.render.BackpackItemStackRenderer.m_108829_(BackpackItemStackRenderer.java:41) ~[sophisticatedbackpacks-1.19.2-3.18.29.719.jar%23182!/:1.19.2-3.18.29.719] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:268) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:417) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109322_(ItemInHandRenderer.java:138) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:339) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default,xf:fml:twilightforest:renderdata,xf:fml:twilightforest:render}
	at net.minecraft.client.renderer.GameRenderer.renderHand(GameRenderer.java:1088) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:1049) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1603) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Yoshinator2'/172306, l='ClientLevel', x=5533.73, y=166.56, z=-2917.42]]
	Chunk stats: 3025, 543
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,131,0), Section: (at 0,3,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4757840 game time, 5265189 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:580) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.58.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Create a diamond backpack.
2. Add the tank upgrade.
3. Add advanced magnet upgrade
4. Add the experience pump upgrade
5. Get 64 bottles of enchanting. Switch to survival.
6. Throw the bottles of enchanting just out of reach of your player so that your backpack absorbs the XP instead of you.
7. Throw the bottles until the game crashes. It shouldn't take too many, maybe around 15.
8. See error as game crashes.

**Expected behavior**
The game does not crash after adding the pump upgrade to the backpack and storing XP.

**Versions**
Mod Version: Latest version (3.18.33.742)
Forge Version: 43.1.58

Please help, this is ruining my and my friends experience :(

**Comment by P3pp3rF1y** [comment]
No it's not tank causing crash but Optifine that removes functionality added by forge. So you need to drop optifine to get this fixed.
