### ISSUE TITLE
Diamond BackPack will not open

### ISSUE THREAD

**Issue by DakaraMCE** [P3pp3rF1y/SophisticatedBackpacks#671]
**Describe the bug**
My diamond backpack will not open anymore.  It wont open via hotkey or right clicking on it.  Other backpacks work to open both ways.  I restarted my game and curseforge.  Its netherite in the picture now because I tried to see if it would work again if I upgraded it.  No dice. 

**To Reproduce**
I dont know how to reproduce this.

**Expected behavior**
I expect the backpack to open and show me its contents.

**Screenshots**
![image](https://user-images.githubusercontent.com/18536648/209422891-a1684354-1489-4265-be26-40b1a16f8200.png)

**Versions**
![image](https://user-images.githubusercontent.com/18536648/209422903-b5a778ae-6ff0-4f28-804c-7758afe0a064.png)

**Comment by P3pp3rF1y** [comment]
Could you check if anything is getting logged in debug.log when you try to open your backpack?

**Comment by DakaraMCE** [comment]
> Could you check if anything is getting logged in debug.log when you try to open your backpack?

Here it is:

13:13:08.032
net.minecraft.network.protocol.PacketUtils
Server thread
Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@65cf3409, suppressing error
java.lang.NullPointerException: Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null
	at TRANSFORMER/immersiveengineering@1.19.2-9.1.0-156/blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.matches(ShaderBagRecipe.java:45)
	at TRANSFORMER/immersiveengineering@1.19.2-9.1.0-156/blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.m_5818_(ShaderBagRecipe.java:26)
	at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager$RecipeNode.matches(AuxRecipeManager.java:190)
	at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager$LinkedRecipeList.findFirstMatch(AuxRecipeManager.java:160)
	at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:64)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.updateCraftingResult(CraftingUpgradeContainer.java:112)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onCraftMatrixChanged(CraftingUpgradeContainer.java:101)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onInit(CraftingUpgradeContainer.java:97)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.addUpgradeSettingsContainers(StorageContainerMenuBase.java:125)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.initSlotsAndContainers(StorageContainerMenuBase.java:111)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.<init>(StorageContainerMenuBase.java:102)
	at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.<init>(BackpackContainer.java:36)
	at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$use$9(BackpackItem.java:287)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25)
	at TRANSFORMER/forge@43.2.1/net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:201)
	at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:287)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by P3pp3rF1y** [comment]
So I am not sure what exactly you have in the crafting grid, but it appears that immersive engineering's ShaderBagRecipe has an issue with it probably because it uses some custom rarity that there's no shader bag defined for.

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.19.2/src/main/java/blusunrize/immersiveengineering/common/crafting/ShaderBagRecipe.java#L45

So you will need to report this to them with this stacktrace above which should be enough to fix.

Also that appears to be breaking in code that was very recently changed in IE so it seems that downgrading to previous version should fix the issue for you until IE has this fixed.

**Comment by DakaraMCE** [comment]
Just wanted to confirm you are 100% correct, I downgraded IE and my backpack opens.  It was a latex bucket in the crafting grid. 
Thanks a super ton for the help!

**Comment by P3pp3rF1y** [comment]
yup that would do it, checked the industrial foregoing code and there's definitely custom rarities for items there.
