### ISSUE TITLE
[1.20.1]cannot install , need help

### ISSUE THREAD

**Issue by Alexios-cd** [P3pp3rF1y/SophisticatedBackpacks#809]
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/11305545/662cef3b-48ab-432e-bf46-b14d85cc28ef)
     

Mod List: 
                server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: NOSIGNATURE
                forge-1.20.1-47.0.19-universal.jar                |Forge                         |forge                         |47.0.19             |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90[07:48:07] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mod §esophisticatedbackpacks§r requires §6sophisticatedcore§r §o1.20.1-0.5.62 or above§r
§7Currently, §6sophisticatedcore§r§7 is §o§nnot installed
]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:149) ~[fmlcore-1.20.1-47.0.19.jar%23108!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.20.1-47.0.19-universal.jar%23112!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23107!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}

**Comment by P3pp3rF1y** [comment]
You need to add sophisticatedcore as well, which is exactly what this message tells you, it's shown as required dependency in backpacks download and mod launchers will do this for your automatically.

**Comment by Alexios-cd** [comment]
Thank you very much, I solved it.
