### ISSUE TITLE
Adding SB to Fantasy Modpack mod folder causes crash before single/multi world selection screen

### ISSUE THREAD

**Issue by WPBickham1** [P3pp3rF1y/SophisticatedBackpacks#913]
Describe the Bug
When Sophisticated Backpacks is added to mod folder it causes the modpack to crash when loading before single/multi game screen. Backpacked in or out of mod folder has same effect.

Reproduction Steps
...

Screenshots and Videos
No response

Crash Report or Log
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/21/23, 5:42 PM
Description: Rendering overlay

java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.fabric.citresewn.CITResewn.INSTANCE" is null
	at net.minecraft.client.resources.model.ModelBakery.handler$epa000$initCITs(ModelBakery.java:678) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citresewn.mixins.json:core.ModelLoaderMixin,pl:mixin:APP:snowrealmagic.mixins.json:ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:placebo.mixins.json:ModelBakeryMixin,pl:mixin:APP:citresewn.mixins.json:cititem.ModelLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:501) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citresewn.mixins.json:core.ModelLoaderMixin,pl:mixin:APP:snowrealmagic.mixins.json:ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:placebo.mixins.json:ModelBakeryMixin,pl:mixin:APP:citresewn.mixins.json:cititem.ModelLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:173) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citresewn.mixins.json:core.ModelLoaderMixin,pl:mixin:APP:snowrealmagic.mixins.json:ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:placebo.mixins.json:ModelBakeryMixin,pl:mixin:APP:citresewn.mixins.json:cititem.ModelLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:61) ~[forge-1.18.2-40.2.10-universal.jar%23334!/:?] {re:classloading}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:snowrealmagic.mixins.json:ModelManagerMixin,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:snowrealmagic.mixins.json:ModelManagerMixin,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,re:classloading,pl:mixin:APP:drippyloadingscreen.mixin.json:client.IMixinSimplePreparableReloadListener,pl:mixin:APP:immediatelyfast.mixins.json:fast_text_lookup.ISinglePreparationResourceReloader,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat1192minus.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
Mixins in Heaven:
	net.minecraft.client.renderer.GameRenderer:
		net.coderbot.iris.mixin.GameRendererAccessor (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (mixins.oculus.json)
		me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (sodium-extra.mixins.json)
		virtuoel.pehkui.mixin.client.compat115plus.GameRendererMixin (pehkui.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinGameRenderer (shouldersurfing.mixins.json)
		team.lodestar.lodestone.mixin.GameRendererMixin (lodestone.mixins.json)
		virtuoel.pehkui.mixin.client.compat115plus.compat1192minus.GameRendererMixin (pehkui.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (mixins.oculus.json)
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat1192minus.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23329!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

Mixins in Heaven:
	net.minecraft.client.renderer.GameRenderer:
		net.coderbot.iris.mixin.GameRendererAccessor (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (mixins.oculus.json)
		me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (sodium-extra.mixins.json)
		virtuoel.pehkui.mixin.client.compat115plus.GameRendererMixin (pehkui.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinGameRenderer (shouldersurfing.mixins.json)
		team.lodestar.lodestone.mixin.GameRendererMixin (lodestone.mixins.json)
		virtuoel.pehkui.mixin.client.compat115plus.compat1192minus.GameRendererMixin (pehkui.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (mixins.oculus.json)
	net.minecraft.client.Minecraft:
		com.teampotato.redirector.mixin.net.minecraft.client.MinecraftMixin (redirector.mixins.json)
		fuzs.puzzleslib.mixin.client.MinecraftForgeMixin (puzzleslib.forge.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		shcm.shsupercm.fabric.citresewn.mixin.citenchantment.MinecraftClientMixin (citresewn.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.oculus.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (modernfix-common.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (memoryleakfix.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.MixinMinecraft (drippyloadingscreen.mixin.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.oculus.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (memoryleakfix.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientAccessor (bettercombat.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.IMixinMinecraft (drippyloadingscreen.mixin.json)
		org.embeddedt.modernfix.forge.mixin.feature.measure_time.MinecraftMixin_Forge (modernfix-forge.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		com.teampotato.opotato.mixin.keybind.MixinMinecraft (opotato.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.blast_search_trees.MinecraftMixin (modernfix-common.mixins.json)
		dev.architectury.mixin.forge.MixinMinecraft (architectury.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.oculus.json)
		io.github.thecsdev.tcdcommons.client.mixin.MixinMinecraftClient (tcdcommons.client.mixins.json)
		com.yungnickyoung.minecraft.travelerstitles.mixin.MinecraftClientTickMixin (travelerstitles.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientInject (bettercombat.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (rubidium.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_leaks.MinecraftMixin (modernfix-common.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReload (entity_model_features-common.mixins.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (modernfix-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (modernfix-common.mixins.json)
		de.cheaterpaul.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		com.teamabnormals.blueprint.core.mixin.client.MinecraftMixin (blueprint.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		com.biomemusic.mixin.ClientMusicChoiceMixin (biomemusic.mixins.json)
		fuzs.puzzleslib.mixin.client.accessor.MinecraftAccessor (puzzleslib.common.mixins.json)
		de.keksuccino.konkrete.mixin.client.MixinMinecraft (konkrete.mixin.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.hud_batching.MixinMinecraftClient (immediatelyfast.mixins.json)
		fuzs.resourcepackoverrides.mixin.client.MinecraftMixin (resourcepackoverrides.common.mixins.json)
	net.minecraft.client.main.Main:
		com.ccr4ft3r.lightspeed.mixin.MinecraftMainMixin (lightspeed.mixins.json)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, §b§lTetra_GUI_v.0.7.1.zip, HIDYKs REALM.zip, Minecolonies Refreshed-1.18.2-1.1.zip, Pinnacle 2.7.1.zip, Adventurer'sChest[Lootr].zip, waystones.zip, Frozy's Quest Book.zip, [1.3] Enhanced Boss Bars.zip, Dungeons Icons 1.0.zip, 3D Tankards.zip, BoxyBubbles4PGA_1.18.2-1.0.2.zip, DARK EmbellishedStone.zip, EclecticTrove-noconfig-1.18-1.2.0.zip, NoBushyLeaves.zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.fabric.citresewn.CITResewn.INSTANCE" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.fabric.citresewn.CITResewn.INSTANCE" is null
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.resources.model.ModelBakery.handler$epa000$initCITs(ModelBakery.java:678)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:501)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:173)
	at TRANSFORMER/forge@40.2.10/net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:61)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 591754856 bytes (564 MiB) / 1400897536 bytes (1336 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22462.34
	Virtual memory used (MB): 9023.46
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 12.18
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8064m -Xms256m
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: forge-40.2.10
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 

Operating System
Windows 10

Minecraft Version
1.18

Modloader
Forge

Modpack Version
V3

Optifine
No

Other Mods
None

**Comment by P3pp3rF1y** [comment]
Looks like you have some fabric mod there that's crashing you, you will need to figure that one out as it has nothing to do with sophisticated `shcm.shsupercm.fabric.citresewn.CITResewn.INSTANCE`
