### ISSUE TITLE
Backpack kicks people out of the server

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#947]
**Describe the bug**

When players move things around from their backpack to their inventory they get disconnected, not crash. It's completely random, not the same everytime, doesn't happen everytime.

Crash log if it's a crash.
https://paste.ee/p/u3z9M Here's their logs, I didn't see anything troubling in them but you might

**To Reproduce**
1. Open backpack
2. Move things around in your inventory
3. Get kicked from server
4. Some say it's upgrades that do it, like the smelter or some filters.

**Expected behavior**
To not kick players from the server.

**Versions**
Minecraft 1.20.1
Forge: 47.2.16
Mod Versions: 
SB: 3.19.4.978 (We tried using the latest on above this and it kicked them a lot more)
SC: 0.5.111.517

**Comment by P3pp3rF1y** [comment]
So player being kicked isn't normal behavior and thus I can't recreate and will need more info on how I can or log that shows what was logged when it happened. The log shared appears to be just for loading minecraft instance before player even joins a server.

**Comment by ghost** [comment]
https://mclo.gs/f2ggkdN Here's logs of them joining the server, then getting kicked out. I've had more reports of people getting kicked out taking off the backpack, and some just moving stuff around with the filter upgrade/just left clicking and moving stuff.

**Comment by P3pp3rF1y** [comment]
> https://mclo.gs/f2ggkdN Here's logs of them joining the server, then getting kicked out. I've had more reports of people getting kicked out taking off the backpack, and some just moving stuff around with the filter upgrade/just left clicking and moving stuff.

That log doesn't show anything related to SB, it appears to show reloading client side resources which seems to cause some issue at the end but I fail to see how that could be related to SB. If you have a log that shows SB related stuff or have a way to recreate let me know

**Comment by ghost** [comment]
[08Jan2024 18:34:15.902] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Poopdude911 lost connection: Internal Exception: java.lang.StackOverflowError

It is being used in a server. While the auto smelter upgrade is in progress or if it has recently been used, moving the mod off the upgrade slot with a left click causes the game to disconnect them from the server.

**Comment by P3pp3rF1y** [comment]
> [08Jan2024 18:34:15.902] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Poopdude911 lost connection: Internal Exception: java.lang.StackOverflowError
> 
> It is being used in a server. While the auto smelter upgrade is in progress or if it has recently been used, moving the mod off the upgrade slot with a left click causes the game to disconnect them from the server.

I will need way more info than this as I am able to use the upgrade and move it around without any issue. Seeing the full log when this happens would be helpful to understand what actually happened.

**Comment by ghost** [comment]
ive noticed this issue happen with the tool swapper upgrade as well but it is harder to replicate. when switching the tool swapper upgrade off (leaving the mod upgrade in place just turning the switch off), then left clicking a tool from the backpack, it will cause a crash

**Comment by ghost** [comment]
> > [08Jan2024 18:34:15.902] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Poopdude911 lost connection: Internal Exception: java.lang.StackOverflowError
> > It is being used in a server. While the auto smelter upgrade is in progress or if it has recently been used, moving the mod off the upgrade slot with a left click causes the game to disconnect them from the server.
> 
> I will need way more info than this as I am able to use the upgrade and move it around without any issue. Seeing the full log when this happens would be helpful to understand what actually happened.

https://mclo.gs/QNwGAjA#L23108 Here are the server side logs since their client side logs don't show anything. Hopefully these help.

**Comment by P3pp3rF1y** [comment]
again unable to recreate that tool swapper thing so that's specific to your pack and I will need log for that. And that latest log doesn't include the issue that was mentioned before (at least I can't find `StackOverflowError` anywhere in that log) so I will need something that could provide clues as to what is happening.

**Comment by ghost** [comment]
[08Jan2024 18:33:47.928] [Server thread/INFO] [cobblemonchallenge/]: Battle victory!
[08Jan2024 18:33:48.654] [User Authenticator #84/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player VhBarbosa18 is d0854762-af77-4eb0-a2fa-6863003d205d
[08Jan2024 18:33:48.976] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@748c79f4[id=d0854762-af77-4eb0-a2fa-6863003d205d,name=VhBarbosa18,properties={textures=[com.mojang.authlib.properties.Property@71a66c37]},legacy=false] (/201.17.120.138:3193) lost connection: Disconnected
[08Jan2024 18:34:00.266] [Async Chat Thread - #293/INFO] [Console/]: ꐗ Iceixient: oh its not killing me anymore. the backpack is merciful
[08Jan2024 18:34:01.775] [Server thread/INFO] [cobblemonchallenge/]: Battle victory!
[08Jan2024 18:34:05.496] [Craft Scheduler Thread - 310/INFO] [BuycraftX/]: Sending 1 analytic events
[08Jan2024 18:34:05.976] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Sa2pin issued server command: /pokefishing list
[08Jan2024 18:34:05.976] [Server thread/INFO] [STDOUT/]: Expected safari area... safari area: BlockPos{x=0, y=0, z=0} end: BlockPos{x=3, y=3, z=3}
[08Jan2024 18:34:05.976] [Server thread/INFO] [dev.mikeretriever.cobblemonmikeskills.CobblemonMikeSkills/]: Biome Tag not found on loaded fishing table: is_cave_thundering
[08Jan2024 18:34:05.976] [Server thread/INFO] [dev.mikeretriever.cobblemonmikeskills.CobblemonMikeSkills/]: Biome Tag not found on loaded fishing table: is_cave_raining
[08Jan2024 18:34:05.976] [Server thread/INFO] [dev.mikeretriever.cobblemonmikeskills.CobblemonMikeSkills/]: Biome Tag not found on loaded fishing table: is_cave_night
[08Jan2024 18:34:15.322] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Sa2pin issued server command: /home volcan
[08Jan2024 18:34:15.662] [Server thread/INFO] [Easy NPC/]: Register attribute based objectives for Humanoid['entity.easy_npc.humanoid'/494030, l='ServerLevel[Premium]', x=-5324.50, y=118.00, z=4854.50]
[08Jan2024 18:34:15.902] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Poopdude911 lost connection: Internal Exception: java.lang.StackOverflowError
[08Jan2024 18:34:15.902] [Server thread/INFO] [voicechat/]: [voicechat] Disconnecting client Poopdude911
[08Jan2024 18:34:15.903] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerQuitEvent to QueueSystem v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.1-1.0.2-730181a4.jar%23242!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading}
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.1-1.0.2-730181a4.jar%23242!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.1-1.0.2-730181a4.jar%23242!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,re:mixin}
	at net.minecraft.server.players.PlayerList.handler$znn000$arclight$playerQuitPre(PlayerListMixin.java:1125) ~[server-1.20.1-20230612.114412-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11286_(PlayerListMixin.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerPlayNetHandlerMixin.java:1136) ~[server-1.20.1-20230612.114412-srg.jar%23323!/:?] 
	
Around this section is where it happened. Many players have tested it and it is this, could it be something server related?

**Comment by P3pp3rF1y** [comment]
Ok I can see it now but there's nothing in there that helps finding out what happened. I guess client log may have more info so I can take a look at that to see if it gets me anything otherwise this issue will be ready to be close really because this all seems to be related to your pack / server where something is misbehaving and causing these issues that I haven't heard from anyone else despite many tens or more probably hundreds of thousands of players playing with this mod in 1.20

**Comment by ghost** [comment]
It's okay, just aren't up to that knowledge yet :) I'm sure you'll figure it out one day.

**Comment by P3pp3rF1y** [comment]
well I was trying to help you out to figure out what that may be as I am 99% sure it's something else misbehaving but without necessary info that's impossible task
